### PR TITLE
Has changed and running native image.

### PR DESCRIPTION
**Pull request by kamalkumar789**
Solved this issue. [Issue #30985](https://github.com/spring-projects/spring-framework/issues/30985)

### CODE REVIEW

**Comment by Eng-Fouad** [comment]
This does not solve the issue. Using interfaces instead of classes will only replace CGLIB proxy with JDK dynamic proxy. See: https://docs.spring.io/spring-framework/reference/core/aop/proxying.html

The linked issue is related to CGLIB proxying only.

**Comment by kamalkumar789** [comment]
Then by Aspect annotation, it can be done.

**Comment by Eng-Fouad** [comment]
> Then by Aspect annotation, it can be done.

How to do that?

**Comment by kamalkumar789** [comment]
Assign me and give some time.

**Comment by Eng-Fouad** [comment]
This is just a reproducer project to test the bug. Please clone this repo and apply the fix.

**Comment by kamalkumar789** [comment]
Okay, let me do it.

**Pull request closed without merging**
